### PR TITLE
Issue with managing hyper-v host with no domain

### PR DESCRIPTION
**Pull request by chyiz**
I tried to follow the last section, "Manage a Hyper-V host outside your domain (or with no domain) ", with no success.
It seems that I need to enable the CredSSP server role on hyper-V host and run the original second and third command on the managing PC.
I'm running Windows 10 on both Hyper-V host and managing PC.

### CODE REVIEW

**Comment by muzzar78** [comment]
I logged an issue about this. Check out https://github.com/Microsoft/Virtualization-Documentation/issues/261

**Comment by chyiz** [comment]
@muzzar78 l wish I had found your report when I was trying to figure it out.

**Comment by scooley** [comment]
Thanks for the update :)

**Comment by scooley** [comment]
Also, sorry @muzzar78.  I lost the thread before updating the doc.

**Pull request merged**
