### PR TITLE
Fixing Azure template

### PR DESCRIPTION
**Pull request by PatrickLang**

### CODE REVIEW

**Comment by PatrickLang** [comment]
ping @neilpeterson can you take a look at this adjustment? It's a bit hard to test because the hyperlinks still point to master - not the branch being merged.

**Comment by neilpeterson** [comment]
I've just deployed the updated template. After deployment the docker service is stopped. If this is a know issue without a current workaround (other than manually starting the service), we should be able to add a 'fix' to the template. Let me know, I can help.

```none
PS C:\> get-service docker

Status   Name               DisplayName
------   ----               -----------
Stopped  docker             Docker Engine

PS C:\> start-service docker

PS C:\> docker version

Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```

Images look good, and was able to start a container.

```none
PS C:\> docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
microsoft/windowsservercore   10.0.14393.321      93a9c37b36d0        4 weeks ago         8.68 GB
microsoft/windowsservercore   latest              93a9c37b36d0        4 weeks ago         8.68 GB
microsoft/nanoserver          10.0.14393.321      e14bc0ecea12        4 weeks ago         810 MB
microsoft/nanoserver          latest              e14bc0ecea12        4 weeks ago         810 MB
```

One other note, when I had initially put this together I added an NSG / Firewall rule for 2376. This does not do much good without configuring TLS / Certs etc.. May want to consider removing the rule.

**Comment by PatrickLang** [comment]
The stopped service is a separate known issue, we're working on it. `Start-Service Docker` should succeed

**Comment by neilpeterson** [comment]
Yes, manually starting the service worked fine. 

My thought was that if there will be a delay in having this fixed, a VM extension could be used to automate this step (start-service docker) so that this issue will not be exposed to the end user.

**Comment by PatrickLang** [comment]
I opened another issue on service restarts https://github.com/docker/docker/issues/27696 . Fix is in review :)

**Pull request merged**
