### PR TITLE
Shell prompt does not appear

### PR DESCRIPTION
**Pull request by GoodMirek**
Shell prompt does not appear when docker command is invoked from PowerShell. It works from CMD shell.

### CODE REVIEW

**Comment by rs38** [comment]
I don't think, this is by design and is true for all. I usually call all these commands from powershell

**Comment by GoodMirek** [comment]
Please may you confirm it works for you on Windows Server 2016 with the
latest module "DockerMsftProvider" and the latest package "docker" ?

I have used a fresh new AWS EC2 machine, launched from AMI
"Windows_Server-2016-English-Full-Containers-2016.10.18 (ami-d08edfc7)",
first following this guide:
https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server
and then this guide:
https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_images

Mirek Svoboda | +1 (845) 584-1854  | Skype: xsvobo10

**Comment by rs38** [comment]
I can confirm that at least a EC2 nano Host behaved very strange during my own tests when powershell remoted. It experienced sustained cpu 100% after that docker run commands with nano docker image.

**Comment by GoodMirek** [comment]
Thanks. Seems dust needs to settle a bit.

Mirek Svoboda | +1 (845) 584-1854  | Skype: xsvobo10

**Comment by PatrickLang** [comment]
Can you share an example of what you see when the prompt is missing? I'm getting prompts after running `docker run -it microsoft/nanoserver` from PowerShell for example.

**Comment by GoodMirek** [comment]
I see nothing at the moment when I run `docker run -it microsoft/nanoserver` from PowerShell. When I stop the container then command prompt returns. In W10 on my workstation it works fine, but it is HyperV isolation, not Windows Containers isolation. I tend to believe this is AWS AMI specific issue. I did not install WS2016 elsewhere than on AWS yet, so cannot confirm it.
I will close this issue now and would reopen if able to reproduce elsewhere.

**Pull request closed without merging**
