### PR TITLE
Changed whats_new.md in virtualization/hyperv_on_windows/about

### PR DESCRIPTION
**Pull request by mdragan**
Some improvements.

### CODE REVIEW

**Comment by scooley** [comment]
Thank you :)

**Comment by mdragan** [comment]
Voil.
How fast :)

**Comment by scooley** [comment]
Isn't it great :)?   I love receiving pull requests like this.  Really, thank you for the code cleanup.

**Comment by mdragan** [comment]
Yes it is :)
It was my first pull request, I waited for your comment and I wanted to be sure that I did it correctly :)

**Pull request merged**
