### PR TITLE
Adding IPv6 tip

### PR DESCRIPTION
**Pull request by kallie-b**

### CODE REVIEW

**Comment by StefanScherer** [comment]
Is the debug-containerhost.ps1 script checking for IPv6 already? Otherwise adding thos check would be very helpful.

**Comment by JMesser81** [comment]
LGTM

**Comment by JMesser81** [comment]
@StefanScherer  - we could indeed add that test to the Debug-ContainerHost.ps1 script. @kallie-b  - can you take a look at doing this?

**Comment by kallie-b** [comment]
@scooley -- I thought I merged this but I'm not seeing the update on the live docs. Did I do something wrong here?

**Comment by kallie-b** [comment]
@PatrickLang Looks like Sarah is out--perhaps you know why my merge isn't appearing in the live doc?

**Comment by PatrickLang** [comment]
live isn't actually live. There's one more step in the publishing system that appears to be broken that pulls changes from live to its private repo before rendering. I'll see if I can wake it back up

**Comment by kallie-b** [comment]
Okay, thanks :)

**Pull request merged**
