### PR TITLE
Updated script to include external switch check.

### PR DESCRIPTION
**Pull request by neilpeterson**
Script fails if an external switch is not available. I’ve added a check for external switch, if it does not exist a descriptive error is thrown and the script exits. Function can be extended to include switch creation automation.

### CODE REVIEW

**Comment by mebersol** [comment]
The script succeeds in staging mode without an external switch, as expected.  I think we want to move this down in the script:

if ($SwitchName -ne "")
    {
        Write-Output "Connecting VM to switch $SwitchName"
        $vm | Get-VMNetworkAdapter | Connect-VMNetworkAdapter -SwitchName "$SwitchName"
    }
<-- here if not staging mode, throw the exception

**Comment by scooley** [comment]
Did we ever reach a conclusion about merging this change?

**Comment by neilpeterson** [comment]
I have not had an opportunity to re-visit. Will do so next week.

**Comment by mebersol** [comment]
I've got a fix coming for this

**Comment by mebersol** [comment]
This was addressed with f3d3f6d9e3ae86bc90e05bf1d732b885d14062c4

**Comment by neilpeterson** [comment]
@mebersol, thanks Mike..

**Pull request closed without merging**
