### PR TITLE
Fix VS ref and add backtick escape description

### PR DESCRIPTION
**Pull request by sixeyed**

### CODE REVIEW

**Comment by neilpeterson** [comment]
@sixeyed - thanks for the PR. We have some documentation on escape character options in the following doc.

Good catch on the first fix.

For the escape character fix, we have this documented [here] (https://msdn.microsoft.com/en-us/virtualization/windowscontainers/docker/manage_windows_dockerfile#escape-character). We have a few options here:

- Leave the current doc as is.
- Move the escape character section to the optimize doc - may be a better place for it.
- Add a pointer back to the current doc.

I will be out of office Monday - Thursday but will check back in when I return.

**Comment by neilpeterson** [comment]
@sixeyed if you can pull out the escape character items, I can merge this in.

Perhaps create a second PR for the escape character stuff and @enderb-ms can review.

Thanks

**Comment by sixeyed** [comment]
@neilpeterson I've removed that section now, and I'll add it to a separate PR. Thanks.

**Comment by neilpeterson** [comment]
@sixeyed appreciate it.

**Pull request merged**
