### PR TITLE
fix to resolve errors running on azure

### PR DESCRIPTION
**Pull request by brogersyh**
also restarts docker engine service, so that "docker images" shows something

### CODE REVIEW

**Comment by scooley** [comment]
pinging @mebersol

**Comment by scooley** [comment]
@jterry75 @mebersol @taylorb-microsoft --  anyone know if some equivalent fix has been incorporated into the script/how we should proceed with this PR?

**Comment by PatrickLang** [comment]
Thanks for submitting this. I'm sorry it took so long to get back. I talked to @mebersol to get the back story on this code:

```
               # Workaround for trusted installer thing
                #

                Write-Output "Creating a first boot layer..."

                $dockerFileDir = Join-Path $env:TEMP "dockerTemp"

                md -force $dockerFileDir
```

This was a temporary workaround that was needed between when Technical Preview 5 was released, and when this cumulative update was released: https://support.microsoft.com/en-us/kb/3158987

When that update was rolled out, @mebersol removed the workaround in Install-ContainerHost.ps1. The current script should be ok to run on Azure.

**Comment by PatrickLang** [comment]
I forgot to mention - the current script also restarts the Docker service now. We can go ahead and close this.

**Pull request closed without merging**
