### PR TITLE
Merge Pester tests back into Debug-ContainerHost.ps1

### PR DESCRIPTION
**Pull request by PatrickLang**
Per feedback from #414 - it was hard to download all of the files needed to run the tests without cloning the full repo. I looked into various solutions and agree with @StefanScherer and @taylorb-microsoft that it's probably easiest to just publish a single file.

This merges everything back into one file, and doesn't change any code.

### CODE REVIEW

**Comment by PatrickLang** [comment]
Ping @jterry75 - any concerns?

**Comment by StefanScherer** [comment]
This makes it super easy to get the latest version of that check. Just tried it in Azure:

bildschirmfoto 2016-10-12 um 22 01 34

**Comment by PatrickLang** [comment]
@StefanScherer Thanks! Did those errors cause any problems? I don't recall seeing the Resolver... error before.

**Comment by StefanScherer** [comment]
@PatrickLang After creating the Azure VM and RDPing into it, a `docker version` only showed the client version. The docker deamon was not running. I just ran `start-service docker` and everything is fine since then, even after a reboot.

**Comment by StefanScherer** [comment]
Anything you want to investigate?

**Comment by PatrickLang** [comment]
@StefanScherer I see it too. I'll take that up with the right team.


```none
PS C:\Users\patrick> wget https://raw.githubusercontent.com/Microsoft/Virtualization-Documentation/5429b3fa25a95cac7afb1
a52cabc5a6d7eef757a/windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1 -OutFile Debug-ContainerH
ost.ps1
PS C:\Users\patrick> .\Debug-ContainerHost.ps1
Checking for common problems
Describing Windows Version and Prerequisites
 [+] Is Windows 10 Anniversary Update or Windows Server 2016 818ms
 [+] Has KB3192366, KB3194496, or later installed if running Windows build 14393 206ms
 [+] Is not a build with blocking issues 33ms
Describing Docker is installed
 [+] A Docker service is installed - 'Docker' or 'com.Docker.Service'  107ms
 [-] Service is running 206ms
   Expected: {Running}
   But was:  {Stopped}
   28:         $service.Status | Should Be Running
   at <ScriptBlock>, C:\Users\patrick\Debug-ContainerHost.ps1: line 28
 [+] Docker.exe is in path 1.44s
Describing User has permissions to use Docker daemon
 [+] docker.exe should not return access denied 59ms
Describing Windows container settings are correct
 [+] Do not have DisableVSmbOplock set 54ms
 [+] Do not have zz values set 35ms
Describing The right container base images are installed
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/images/json: open //./pipe/docker_engine: The syst
em cannot find the file specified.
 [-] At least one of 'microsoft/windowsservercore' or 'microsoft/nanoserver' should be installed 179ms
   ValidationMetadataException: The argument is null or empty. Provide an argument that is not null or empty, and then t
ry the command again.
   ParameterBindingValidationException: Cannot validate argument on parameter 'Property'. The argument is null or empty.
 Provide an argument that is not null or empty, and then try the command again.
   at <ScriptBlock>, C:\Users\patrick\Debug-ContainerHost.ps1: line 76
Warnings & errors from the last 24 hours


   ProviderName: docker

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
10/12/2016 8:57:05 PM            4 Error            fatal: Error starting daemon: Error initializing network control...
```

**Comment by PatrickLang** [comment]
Talked to Justin, he thinks it seems reasonable

**Pull request merged**
