### PR TITLE
Add section to install Windows Updates

### PR DESCRIPTION
**Pull request by sixeyed**
Without this step, with the evaluation version of Windows Server 2016 I was unable to run any containers.

### CODE REVIEW

**Comment by neilpeterson** [comment]
@enderb-ms

**Comment by taylorb-microsoft** [comment]
@enderb-ms and @neilpeterson  - in general this looks like a good commit.  We are going to add that check to the OneGet provider but until that's online make sure the updates are installed is good. 

Ideally I'd prefer a PowerShell option but in absence this is a lot better than nothing.

**Comment by scooley** [comment]
@sixeyed mind merging in changes :)?

**Comment by sixeyed** [comment]
@scooley - merged in now - I was way behind!

**Comment by scooley** [comment]
Thanks!  Sorry for the super slow merge :)

**Comment by doggy8088** [comment]
@scooley @PatrickLang I think this `Windows Updates` section should move to the first section.

**Pull request merged**
