### PR TITLE
Added clarification about Hyper-v Containers

### PR DESCRIPTION
**Pull request by kparca**
Explaining that Hyper-V containers run specialized VM's which at the time being are limited to Windows but techinically can run no-windows if optimied

### CODE REVIEW

**Comment by scooley** [comment]
I think this is a good note to add but adding people for word smithing @taylorb-microsoft @enderb-ms @mylesbkeating1993 @PatrickLang

**Comment by taylorb-microsoft** [comment]
I submitted a recommended clarification to @kparca's PR.

**Comment by scooley** [comment]
Doc has been completely rewritten since this was posted.  Mind if I close the PR?

**Comment by kparca** [comment]
Yes please go ahead and close it. Thx


________________________________

**Pull request closed without merging**
