### PR TITLE
Update app_compat.md

### PR DESCRIPTION
**Pull request by perrysk-msft**
Update SQL Server Express table entry.

### CODE REVIEW

**Comment by scooley** [comment]
Can we add the docker file to [here](https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-server-container-samples)?

If it's actively developed there, I can also make a subtree to keep the clone here in sync.

**Comment by scooley** [comment]
Sorry, I'm having no luck pulling in your files and keeping their commit history :(.  I'm going to try a few more approaches.

**Comment by scooley** [comment]
I give.  Project for another day.  I'll file an issue.

**Comment by perrysk-msft** [comment]
Thanks Sarah!

On Mar 10, 2016, at 5:31 PM, Sarah Cooley <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #159<https://github.com/Microsoft/Virtualization-Documentation/pull/159>.

-

**Pull request merged**
