### PR TITLE
Configure Network section instruction needs an update

### PR DESCRIPTION
**Pull request by rbinrais**
The "Configure Network" section has a powershell instruction but powershell.exe part is missing from it. This results in error when this instruction is use as-is.

### CODE REVIEW

**Comment by neilpeterson** [comment]
Hey rbinrais - when I run this in a command prompt, I am receiving the following error:

```bash
INFO: Could not find files for the given pattern(s).
```

I have updated the text of the article with a hint about PowerShell, and can create a work item to dig into the command, but will take a few days. Feel free to adjust, or set me straight if I am doing something incorrect here.

**Comment by rbinrais** [comment]
Double quotes seems to be causing the issue. I manage to resolve the issue by replacing double quotes with single quotes within the command and it runs successfully with expected behavior. 

Following is the working/updated command:

`powershell.exe “if(!(Get-NetFirewallRule | where {$_.Name -eq ‘TCP80’})) { New-NetFirewallRule -Name ‘TCP80’ -DisplayName ‘HTTP on TCP/80’ -Protocol tcp -LocalPort 80 -Action Allow -Enabled True }”`

**Comment by neilpeterson** [comment]
Sorry for the delay here, yep confirmed here as well. Would you like do update the PR and then i will merge?

Thanks

neilp

**Comment by rbinrais** [comment]
Niel - I've updated the pr with the working command. 

Regards,
Razi

**Comment by scooley** [comment]
Hey @rbinrais, we edited that since then...could you merge in upstream/live and resolve the merge conflict?  I could pull your changes across

**Comment by scooley** [comment]
@rbinrais -- I manually merged this in to resolve the conflict...if you could run a quick merge upstream live in the future it's appreciated :)

**Comment by rbinrais** [comment]
Thanks Scooley! will keep that in mind for future updates :)

**Pull request merged**
