### PR TITLE
Update docker version to download

### PR DESCRIPTION
**Pull request by omidkrad**

### CODE REVIEW

**Comment by StefanScherer** [comment]
duplicate of #488. The plan is to use 1.13.0-rc1

**Comment by omidkrad** [comment]
Few other notes:

In section **2. Install Docker**
When docker zip file is downloaded and added to the path, it is ignored because there is another one installed under windows.

```
PS C:\> $env:path += ";c:\program files\docker"
PS C:\> where.exe docker
C:\Windows\System32\docker.exe
c:\program files\docker\docker.exe
PS C:\> docker --version
Docker version 1.12.0-dev, build 8e92415
PS C:\> & 'C:\Program Files\docker\docker.exe' --version
Docker version 1.14.0-dev, build 2b680b1
```

Section **3. Install Base Container Images**
It does not work
```
PS C:\> docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver
5496abde368a: Retrying in 20 seconds
482ab31872a2: Retrying in 20 seconds
Using default tag: latest
latest: Pulling from microsoft/nanoserver
5496abde368a: Downloading
482ab31872a2: Downloading
unknown blob
PS C:\> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
PS C:\> docker run -it microsoft/nanoserver cmd
Unable to find image 'microsoft/nanoserver:latest' locally
latest: Pulling from microsoft/nanoserver
5496abde368a: Downloading
482ab31872a2: Downloading
C:\WINDOWS\system32\docker.exe: unknown blob.
See 'C:\WINDOWS\system32\docker.exe run --help'.
PS C:\>
```

**Comment by StefanScherer** [comment]
@omidkrad Interesting, how does `docker.exe` appear in Windows directory? Which version do you have there, which platform you are working with (eg. Win10 + Docker for Windows ...).
I haven't seen that the docker.exe is in Windows directory.

**Comment by omidkrad** [comment]
@StefanScherer I'm using Windows 10 (Version 1607 build 14393.447) I had **Containers** in Windows Features installed. I think `C:\Windows\System32\docker.exe` comes from there.

**Comment by StefanScherer** [comment]
@omidkrad I can't reproduce that as I often rebuild a Windows 10 machine with [these steps](https://github.com/StefanScherer/docker-windows-beta/blob/643b307d87d4bf6172fffcf8f36b4c277aced399/Vagrantfile#L7-L9). There is no docker installation built-in with these two Windows features.

What is the version of that file?

```
c:\Windows\system32\docker.exe --version
```

Is there a `dockerd.exe` as well?
You should remove both from the windows directory.

**Comment by omidkrad** [comment]
Version is 1.12.0-dev. There was a `dockerd.exe` too and I removed both of them. Then removed and reinstalled Containers feature again and they didn't come back. So I'm not sure where they came from.

After restarting Windows now I'm getting another weird error:
```
PS C:\> Start-Service docker
PS C:\> Get-Service docker

Status   Name               DisplayName
------   ----               -----------
Running  docker             Docker Daemon


PS C:\> docker pull microsoft/nanoserver
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.26/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.). Using system default: https://index.docker.io/v1/
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.26/images/create?fromImage=microsoft%2Fnanoserver&tag=latest: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Pull request closed without merging**
