### PR TITLE
use faster download mechanism

### PR DESCRIPTION
**Pull request by friism**

### CODE REVIEW

**Comment by neilpeterson** [comment]
LGTM, adding @enderb-ms for PG sign off.

**Comment by enderb-ms** [comment]
I tested it out with Measure-Command and, from ten runs for each way, the average time on my VM was:
- Start-BitsTransfer: 4,44.30329 milliseconds
- Invoke-WebRequest: 4,113.84662 milliseconds

But either way, we are closer to getting Invoke-WebRequest working on Nano Server than Starts-BitsTransfer, so I think it would be best if we used the same command throughout the different SKU's.

**Comment by friism** [comment]
@enderb-ms ah sorry - Invoke-WebRequest used to be super slow, but maybe that changed: https://blog.jourdant.me/post/3-ways-to-download-files-with-powershell

**Comment by neilpeterson** [comment]
@enderb-ms thanks for the in depth look. Based on you findings and thoughts about going forward, I am going to close the PR.

**Pull request closed without merging**
