### PR TITLE
Update docker file apache-http-php software versions

### PR DESCRIPTION
**Pull request by mrdotmoon**
Previous version's vc11 and php cannot be downloaded.

### CODE REVIEW

**Comment by scooley** [comment]
@neilpeterson

**Comment by neilpeterson** [comment]
Hey @mrdotmoon, have you been able to build and run an image from the dockerfile? IT built find for me, but is throwing an error when hitting the http endpoint.

I've only done a very quick test, and have not dug into any potential. Issue. I can look at it as soon as I have some time.

```none

Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Unknown: Failed opening required 'C:/www/index.php' (include_path='.;C:\php\pear') in Unknown on line 0
```

**Comment by mrdotmoon** [comment]
Yes, I build it and find the same issue.. After some investigation, if I recreate the folder c:\www in container after running the container, the issue will be gone. So I believe it maybe possible bug for windows container.. I have not compared the ACLs that created in dockerfile and directly in container, but I think it may be the root cause.

**Comment by neilpeterson** [comment]
Yep, that lines up with a know ACLs bug. I will check status and also see if there is a potential work around for the dockerfile.

**Comment by neilpeterson** [comment]
@mrdotmoon I'm going to merge this in. The issue is related to the resulting container and not the Dockerfile. This sample was built in TP4, the issues is specific to TP5. We have engineers looking at the bug now.

Thanks.

**Pull request merged**
