### PR TITLE
Fix .wim file downloading everytime

### PR DESCRIPTION
**Pull request by ivangonzalezvilaboa**
Test-path used against the URI and not the local path.

### CODE REVIEW

**Comment by mebersol** [comment]
Ivan, would this block ever execute on a single machine more than once?  The Test-Path check is really for users who override -WimPath to a local file, I want to fall through and re-download the WIM otherwise because it may have changed.

**Comment by ivangonzalezvilaboa** [comment]
Hi Mike,

Understood. We had a problem with something failing in "Install-ContainerOsImage". We ran the script several times and it was downloading the .wim all the time. But we missed the WinPath as a parameter. I did the change to avoid the script to download the .wim all the time, something we can do using the WinPath parameter.

FYI, something failed running "Install-ContainerOsImage" and the script was failing in that step all the time saying that there was an existing image but we couldn't see that image with Get-ContainerImage.

We modified the script locally to "Uninstall-ContainerOsImage" but the problem was which name to use. Finally we saw that the error was reporting the name and we were able to uninstall the container os image and install it again correctly.

Probably something wrong in our environment but just for you to know if it helps.

Thanks a lot for your time!

**Comment by mebersol** [comment]
Thanks for the report - did you uninstall the image using Uninstall-ContainerOsImage or by deleting the folder?

**Comment by ivangonzalezvilaboa** [comment]
We used Uninstall-ContainerOsImage. We were not able to delete the folder using Windows Explorer

**Comment by mebersol** [comment]
I think we might take a fix to uninstall a half-installed containerOsImage, but it isn't clear to me where in the script this error took place.  If you have the logs, please reopen the issue.

**Pull request closed without merging**
