### PR TITLE
Build dockerized NanoServerApiScan tool

### PR DESCRIPTION
**Pull request by StefanScherer**
After some investigations why running [MongoDB in a nanoserver](https://jira.mongodb.org/browse/SERVER-27182) Docker image does not work, I found the blog post of the [NanoServerApiScan](https://blogs.technet.microsoft.com/nanoserver/2016/04/27/nanoserverapiscan-exe-updated-for-tp5/) tool which might help to fix the problem.

We need a dockerized version of this tool, so testing own Exe files and DLL's can be done much easier.
Many thanks to @brycem who created the [workaround to install the Windows 10 SDK](https://github.com/brycem/PowerShell/blob/400a709ac45737a98eae92b49379b40f04871acb/docker/nightly/windowsservercore/Dockerfile#L45-L92) inside a windowsservercore image.

How about pushing such image to Docker Hub?
I don't know if the tool really needs all of the `Windows Kits/10` folder.

## Usage

There are two variants to run the scanner.

### Use volume

Bind mount the directory with your Exe files to scan to `C:\scan` into the container.

```
docker run -v "$(pwd):C:\scan" nanoserverapiscan
```

### Use onbuild

If you can't use `-v` for example if you are using a remote Windows Docker engine
you can use the onbuild variant instead.

Create a small Dockerfile with the following line in the directory of your
binaries to scan.

```Dockerfile
FROM nanoserverapiscan:onbuild
```

Then build a Docker image with your binaries and then run the container to
scan all binaries.

```
docker build -t scan .
docker run scan
```

## Build the nanoserverapiscan images

```powershell
docker rm -f nano
docker create --name nano microsoft/nanoserver
if (Test-Path tmp) { rm -recurse -force tmp }
mkdir tmp
docker cp nano:Windows/System32/Forwarders tmp

docker build -t nanoserverapiscan .
docker build -t nanoserverapiscan:onbuild onbuild
```

### CODE REVIEW

**Comment by StefanScherer** [comment]
In the meantime I have created a much smaller Docker image with an intermediate Dockerfile to download and install the Windows 10 SDK and then COPY deploy only the directories with the `.lib` files needed by the tool with the final Dockerfile.

The sources are here: https://github.com/StefanScherer/dockerfiles-windows/tree/master/nanoserverapiscan

Please let me know if it's ok to keep that image on Docker Hub or if you want to provide a more official image yourself.

**Comment by PatrickLang** [comment]
@mylesbkeating1993 can you review and merge this?

**Comment by brycem** [comment]
Total Hammer!  Nice work @StefanScherer :-)

**Comment by scooley** [comment]
@PatrickLang @mylesbkeating1993 @taylorb-microsoft Any reason not to merge?

**Comment by PatrickLang** [comment]
Looks good to me

**Pull request merged**
