### PR TITLE
Remove TP5 Nano page

### PR DESCRIPTION
**Pull request by mgreenegit**

### CODE REVIEW

**Comment by neilpeterson** [comment]
@enderb-ms - Ender can we remove, or just update at this point?

**Comment by scooley** [comment]
@enderb-ms

**Comment by PatrickLang** [comment]
Looks like this is on the [microsoft/nanoserver](https://hub.docker.com/r/microsoft/nanoserver/) repo description now

**Comment by PatrickLang** [comment]
No references to the page. LGTM

**Comment by rs38** [comment]
may be a bit off topic but may some of you knows out of the box:  why was there such a big increase in size with the last kumulative update of nanu?

**Pull request merged**
