### PR TITLE
Docker service fails to start if the ProgramData\docker directory does not exist.

### PR DESCRIPTION
**Pull request by jiggstrom**
Added powershell command to create the directory in the documentation.

### CODE REVIEW

**Comment by friism** [comment]
Hm, I don't think this should be required - the daemon should create the directory if it's missing...

**Comment by jhowardmsft** [comment]
Indeed. I was going to fix that today.

**Comment by jiggstrom** [comment]
I've tried it today on two computes which had not run Docker previously, with this error in the eventlog:
fatal: Error starting daemon: open C:\ProgramData\docker\docker.pid: The system cannot find the path specified.

**Comment by jhowardmsft** [comment]
Yes it's bug I introduced last week on master.

**Comment by jhowardmsft** [comment]
Fixed by https://github.com/docker/docker/pull/27690

**Pull request closed without merging**
