### PR TITLE
make the running container interactive

### PR DESCRIPTION
**Pull request by rs38**

### CODE REVIEW

**Comment by rs38** [comment]
I just learned an alternate way to access the image interactively: 
`docker run -it --entrypoint powershell microsoft/iis`

**Comment by PatrickLang** [comment]
@enderb-ms can you take a look? I think ENTRYPOINT servicemonitor.exe was added to `microsoft/iis` since the doc was created

**Comment by PatrickLang** [comment]
Also under discussion - https://github.com/Microsoft/iis-docker/pull/9

**Comment by PatrickLang** [comment]
@rs38 - I'm sorry we left this open so long. I have been trying to catch back up on PRs & issues this week and had to create an alternate version in #522 because we moved some content around. If you have any feedback, can you add it there? I'm going to close this PR and merge #522 instead soon. Thanks for your help and suggestions in fixing this doc!

**Pull request closed without merging**
