### PR TITLE
Added link for PSDSC in containers

### PR DESCRIPTION
**Pull request by nicholasdille**

### CODE REVIEW

**Comment by PatrickLang** [comment]
Thanks for submitting this PR! I think this is a good resource, but @enderb-ms and I need to review it a bit closer. We need to make sure that:
- It still works on Windows Server 2016 GA
- It's using the appropriate version for Windows 10 (v1.13-dev until v1.13 is released), and Windows Server 2016 (12.2-cs)

It will probably be around 11/14 before we can look at it.

**Comment by scooley** [comment]
Ping @enderb-ms

**Comment by scooley** [comment]
Repinging @PatrickLang

**Comment by PatrickLang** [comment]
Thanks! Looks like a great resource! I liked how you showed splitting the meta-configuration as well since that's a topic many people struggle with starting out in DSC

**Comment by nicholasdille** [comment]
@PatrickLang Thanks for your feedback and for merging :-)

**Pull request merged**
