### PR TITLE
Update containers_welcome.md

### PR DESCRIPTION
**Pull request by olpechuk**
I am testing how external contribution feels and how careful PR reviewers work. Thanks for your patience.

### CODE REVIEW

**Comment by scooley** [comment]
Works :).  Anything you want to try in particular?

**Comment by olpechuk** [comment]
I do not see my change. The PR merge happened 15 hours ago. When will it be published?

**Comment by scooley** [comment]
Will be soon :).  There are no automatic hooks to keep them in sync right now so I had to kick off a script.  I just did that

**Comment by olpechuk** [comment]
I would like to have clear SLA when the content will be published after PR is merged. It would be even better if syncing between public and private repos and publishing comes right after PR merge even if PR merge takes more time and you wait for PR merge until you are ready for all the steps to be done at once. The PR is also not good since I changed the "button" for link in one sentence and still have "button" in the following sentence, so I will do Revert and test it.

**Pull request merged**
