### PR TITLE
New Networking Diagnostics

### PR DESCRIPTION
**Pull request by JMesser81**
Added some new NAT networking checks for internal vNIC, host vNIC with NAT gateway IP assigned, etc to Debug-ContainerHost.ps1

Also created new networking clean-up and log collection script

### CODE REVIEW

**Comment by friism** [comment]
wow, this is cool - thanks @JMesser81 

cc @PatrickLang

**Comment by friism** [comment]
looks like there are some problems. Output from my currently f'ed up machine:

```
C:\Program Files\Docker\Docker\resources> .\Debug-ContainerHost.ps1
Checking for common problems
Describing Windows Version and Prerequisites
 [+] Is Windows 10 Anniversary Update or Windows Server 2016 120ms
 [+] Has KB3192366, KB3194496, or later installed if running Windows build 14393 47ms
 [+] Is not a build with blocking issues 41ms
Describing Docker is installed
 [+] A Docker service is installed - 'Docker' or 'com.Docker.Service'  71ms
 [+] Service is running 36ms
 [+] Docker.exe is in path 2.08s
Describing User has permissions to use Docker daemon
 [+] docker.exe should not return access denied 64ms
Describing Windows container settings are correct
 [+] Do not have DisableVSmbOplock set to 1 72ms
 [+] Do not have zz values set 61ms
Describing The right container base images are installed
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/images/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must
be run elevated to connect. This error may also indicate that the docker daemon is not running.
 [-] At least one of 'microsoft/windowsservercore' or 'microsoft/nanoserver' should be installed 123ms
   ValidationMetadataException: The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   ParameterBindingValidationException: Cannot validate argument on parameter 'Property'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   at <ScriptBlock>, C:\Program Files\Docker\Docker\resources\Debug-ContainerHost.ps1: line 96
Describing Container network is created
 [+] At least one local container network is available 1.09s
 [-] At least one NAT, Transparent, or L2Bridge Network exists 133ms
   Expected {0} to be greater than {0}
   187:       $totalnets | Should BeGreaterThan 0
   at <ScriptBlock>, C:\Program Files\Docker\Docker\resources\Debug-ContainerHost.ps1: line 187
 [-] NAT Network's vSwitch is internal 131ms
   Expected: {Internal}
   But was:  {}
   192:       $switchType | Should Be "Internal"
   at <ScriptBlock>, C:\Program Files\Docker\Docker\resources\Debug-ContainerHost.ps1: line 192
 [-] Specified Network Gateway IP for NAT network is assigned to Host vNIC 117ms
   Expected: value to not be empty
   196:       $natGatewayIP | Should Not BeNullOrEmpty
   at <ScriptBlock>, C:\Program Files\Docker\Docker\resources\Debug-ContainerHost.ps1: line 196
 [-] NAT Network's internal prefix does not overlap with external IP' 89ms
   Expected {0} to be greater than {0}
   223:         $hostips.Count | Should BeGreaterThan 0
   at <ScriptBlock>, C:\Program Files\Docker\Docker\resources\Debug-ContainerHost.ps1: line 223
Showing output from: docker info

Showing output from: docker version
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      windows/amd64

Showing output from: docker network ls

Warnings & errors from the last 24 hours
Logs saved to C:\Program Files\Docker\Docker\resources\logs_20161212-171703.csv
```

**Comment by friism** [comment]
@JMesser81 I just tried the force cleanup. It completely grenaded any networking on my windows 10 machine (I wanted to run it because the windows docker daemon wouldn't start because of HNS issue). Windows 10 networking reset and reboot got my back and everything is working now (incl. windows container networking).

**Comment by JMesser81** [comment]
@friism - yes, that's kind of the point. :-) It should only do "container-related" networking however. @viaror to comment further. 

Glad your system is working.

**Comment by viaror** [comment]
@friism @JMesser81
Yes, there is no good way from script to know which switch is owned by vmms or hns. I will investigate it further, if it is feasible to get details on switch ownership.

**Comment by JMesser81** [comment]
@PatrickLang  - you good if I merge these changes? Can you sign-off?

**Comment by scooley** [comment]
I'll ping @PatrickLang :)

**Comment by PatrickLang** [comment]
I'm about to merge these.

I think there are still some odd issues if a machine was ever set up for transparent networking. It fails the check for overlapping subnets in `Debug-ContainerHost.ps1` because $hostips is null.

The cleanup script fails the first time but seems to succeed the second. I'm checking it after a reboot.

**Comment by PatrickLang** [comment]
After a reboot it's better but not totally fixed. Will follow up with you over email so your team can checkout the buggy instance. My other machines are ok

**Pull request merged**
