### PR TITLE
Adding docker version info and error CSV file

### PR DESCRIPTION
**Pull request by PatrickLang**
This adds some new script output and also saves the warning & error logs to a CSV file. 

Here's examples of the new output:
```none
Showing output from: docker version
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   cd0e399
 Built:        Mon Oct 17 22:42:06 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   cd0e399
 Built:        Mon Oct 17 22:42:06 2016
 OS/Arch:      windows/amd64

Showing output from: docker info
Containers: 13
 Running: 0
 Paused: 0
 Stopped: 13
Images: 17
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.899 GiB
Name: plangy
ID: 
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 27
 System Time: 2016-10-19T10:41:59.9775304-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

...

Logs saved to C:\Users\user\Source\Virtualization-Documentation\windows-server-container-tools\Debug-ContainerHost\logs_20161019-104202.csv
```

### CODE REVIEW

**Comment by PatrickLang** [comment]
Ping @jterry75 @enderb-ms @mebersol @StefanScherer anyone available to take a quick look?

**Comment by StefanScherer** [comment]
@PatrickLang Good idea, adding `docker version` and `docker info` to the output.
Here is my current output

```
PS C:\Users\vagrant> wget https://github.com/Microsoft/Virtualization-Documentation/raw/7e440cc7d4746ef9e02d1be93498d7a636cccafd/windows-server-conta
iner-tools/Debug-ContainerHost/Debug-ContainerHost.ps1 -UseBasicParsing | iex
Checking for common problems
Describing Windows Version and Prerequisites
 [+] Is Windows 10 Anniversary Update or Windows Server 2016 556ms
 [+] Has KB3192366, KB3194496, or later installed if running Windows build 14393 173ms
 [+] Is not a build with blocking issues 57ms
Describing Docker is installed
 [+] A Docker service is installed - 'Docker' or 'com.Docker.Service'  62ms
 [+] Service is running 45ms
 [+] Docker.exe is in path 2.06s
Describing User has permissions to use Docker daemon
 [+] docker.exe should not return access denied 49ms
Describing Windows container settings are correct
 [+] Do not have DisableVSmbOplock set to 1 36ms
 [+] Do not have zz values set 78ms
Describing The right container base images are installed
 [+] At least one of 'microsoft/windowsservercore' or 'microsoft/nanoserver' should be installed 176ms
Showing output from: docker version
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Showing output from: docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 40
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 4 GiB
Name: vagrant-2016
ID: FETR:YM2M:AO4T:2AD4:BZUW:TFEW:NASL:KX3U:SR7E:MOSR:3C7G:XPSN
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Warnings & errors from the last 24 hours


   ProviderName: docker

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
10/19/2016 10:36:23 AM           1 Error            Resolver Setup/Start failed for container none, "json: cannot unmarshal array into Go value o...
10/19/2016 10:36:23 AM           1 Warning          [!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOI...


Logs saved to C:\Users\vagrant\logs_20161019-105002.csv
PS C:\Users\vagrant> type .\logs_20161019-105002.csv
#TYPE System.Diagnostics.Eventing.Reader.EventLogRecord
"Message","Id","Version","Qualifiers","Level","Task","Opcode","Keywords","RecordId","ProviderName","ProviderId","LogName","ProcessId","ThreadId","MachineName","UserId","TimeCreated","ActivityId","RelatedActivityId","ContainerLog","MatchedQueryIds","Bookmark","LevelDisplayName","OpcodeDisplayName","TaskDisplayName","KeywordsDisplayNames","Properties"
"Resolver Setup/Start failed for container none, ""json: cannot unmarshal array into Go value of type hcsshim.HNSNetwork""","1",,"0","2","0",,"36028797018963968","303","docker",,"Application",,,"vagrant-2016",,"10/19/2016 10:36:23 AM",,,"application","System.UInt32[]","System.Diagnostics.Eventing.Reader.EventBookmark","Error","Info",,"System.Collections.ObjectModel.ReadOnlyCollection`1[System.String]","System.Collections.Generic.List`1[System.Diagnostics.Eventing.Reader.EventProperty]"
"[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]","1",,"0","3","0",,"36028797018963968","297","docker",,"Application",,,"vagrant-2016",,"10/19/2016 10:36:23 AM",,,"application","System.UInt32[]","System.Diagnostics.Eventing.Reader.EventBookmark","Warning","Info",,"System.Collections.ObjectModel.ReadOnlyCollection`1[System.String]","System.Collections.Generic.List`1[System.Diagnostics.Eventing.Reader.EventProperty]"
```

Just another idea: What about checking if there is a `daemon.json` and showing that content as well?

I've seen some issues with a corrupt `daemon.json` in Docker for Windows.

**Comment by PatrickLang** [comment]
When you say corrupt - were they not parseable, or did they contain options that prevented the service from starting such as a bad path to a TLS cert?

**Comment by StefanScherer** [comment]
This was in a discussion in this blog post https://stefanscherer.github.io/run-linux-and-windows-containers-on-windows-10/ - search for daemon.json. He has Docker for Windows installed and tried for the first time to switch to Windows containers. For any reason he had a daemon.json, but D4Win does not install any. 
Of course users are creative before asking for help. 

So checking/showing daemon.json and the registered command line in the registry would help to see if some misconfiguration has happened.

**Pull request merged**
