### PR TITLE
added warning and recovery guidance for bitlocker users

### LINKED ISSUE #392: BitLocker error 0xc0210000 after installing Hyper-V on Windows 10 client
I was following the Windows 10 Quick Start and encounted the above issue.
There's a thread on MSDN/TechNet on this issues https://social.technet.microsoft.com/Forums/en-US/1a937e9e-19ab-42c6-b314-ecce189c0a08/bitlocker-error-0xc0210000-after-installing-hyperv-on-windows-10-client?forum=mdopmbam

I think the docs need guidance to help people avoid this issue

### PR DESCRIPTION
**Pull request by gavinbarron**
Resolves #392

### CODE REVIEW

**Comment by PatrickLang** [comment]
Hmm, these steps should not be necessary. I have Bitlocker enabled on both my machines and didn't hit this issue. I think the right fix is to check for the right updates first before proceeding rather than disabling the hypervisor and re-enabling it later

**Comment by gavinbarron** [comment]
What are the right updates? I'll happily retry but would appreciate a steer in the right direction.

**Comment by PatrickLang** [comment]
I saw this mentioned on the forum and am trying to determine if and how it's related. Someone else said it fixed their problem, but I'm trying to figure out why. If that is the right fix, I'm hoping we can ask everyone to install this first, and use a bcdedit change as a temporary workaround until the right patch is installed.

Cumulative Update for Windows 10 Version 1607 for x64-based Systems (KB3189866) 
https://support.microsoft.com/en-us/kb/3189866

**Comment by PatrickLang** [comment]
ok, I did find confirmation that the issue was fixed in [KB3176934](http://go.microsoft.com/fwlink/p/?LinkId=825551), which is included in all later update rollups too. The latest is [KB3194496](http://go.microsoft.com/fwlink/p/?LinkId=828777).

The easiest way to tell if you have this installed is to run winver, and look at the OS version number. 14393.222 is the latest as of today and it includes all fixes I mentioned.

**Comment by PatrickLang** [comment]
I added an alternate PR that tells how to avoid the problem. I think it's easier to warn about the problem and ask to double check the OS version and update if needed instead of going straight to the BCDEDIT workaround.

**Comment by gavinbarron** [comment]
Great.

I'm on 14393.51 so that may be the problem. Agreed that if being pro-active
on patch levels is preferable.

**Comment by scooley** [comment]
@PatrickLang @gavinbarron is this still relevant?  If not can I close the PR?

**Comment by PatrickLang** [comment]
Thanks for bringing this up, but I merged in #406 instead. The new instructions in the [Quick Start](https://msdn.microsoft.com/virtualization/windowscontainers/quick_start/quick_start_windows_server) also check this automatically.

**Pull request closed without merging**
