### PR TITLE
Tweak golang image

### PR DESCRIPTION
**Pull request by friism**
I've tried to tweak this image to be more like the official go image. It'd be great to figure out how to fold it into the Docker library image repo (and that's for me/Docker to figure out).

The dependency on .NET is very bad, but I can't get performant downloads any other way. If fast, this would be ideal:

`Invoke-WebRequest -UseBasicParsing -Method Get -Uri https://golang.org/dl/go1.6.windows-amd64.zip | Expand-Archive -DestinationPath c:\\`

Bits-Transfer would be ok too, but https://github.com/docker/docker/issues/21922

### CODE REVIEW

**Comment by StefanScherer** [comment]
@friism Good catch, downloading the ZIP instead of the MSI results in much smaller Docker images (I've done some tests [installing MongoDB](https://github.com/StefanScherer/dockerfiles-windows/tree/master/mongo) in different ways some months ago).

A fast and easy way to download files really helps users to create Dockerfiles like on Linux. I prefer the `wget` shortcut in PowerShell as it is more readable and shorter. It's a shortcut for `Invoke-WebRequest` and sometimes really slow. Does anybody know how to tweak the download speed for that command?

If we improve the golang Docker image it should also contain some developer tools. With only golang inside it is rather useless as you can't install dependencies or build more complex applications in it.

A `go get` needs at least `git` and for private repos also `ssh`. That's why I also added Git for Windows in [my golang Dockerfile](https://github.com/StefanScherer/dockerfiles-windows/blob/e1cbf69a545d6dc64e98cd17e50ddc0ddabfebc8/golang/Dockerfile).

The official [golang 1.6 Dockerfile](https://github.com/docker-library/golang/blob/3cdd85183c0f3f6608588166410d24260cd8cb2f/1.6/Dockerfile) for Linux has the following tools installed on top of golang:
 
[FROM buildpack-deps:jessie-scm](https://github.com/docker-library/buildpack-deps/blob/1845b3f918f69b4c97912b0d4d68a5658458e84f/jessie/scm/Dockerfile) to install git, ssh client, svn, bzr, mercurial
RUN "Download and install gcc and make"
RUN "Download and extract golang 1.6"

**Comment by jhowardmsft** [comment]
Ps is dreadfully slow at downloading. See dockerfile.windows for a MUCH faster way.

**Comment by friism** [comment]
That uses .net webclient too. It's a bad dependency though, because the
dockerfile won't be portable to nano server or other places that don't have
.net

On Monday, April 11, 2016, John Howard <notifications@github.com> wrote:

> Ps is dreadfully slow at downloading. See dockerfile.windows for a MUCH
> faster way.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/Virtualization-Documentation/pull/195#issuecomment-208715579>
>


-- 
http://friism.com/
(650) 318-1051
Sapere aude

**Comment by neilpeterson** [comment]
Michael is also using WebClient in this PR, thanks for the workaround. I will get around to updating the other samples.

From dockerfile.windows
```
  Function Download-File([string] $source, [string] $target) { \
   $wc = New-Object net.webclient; $wc.Downloadfile($source, $target) \
  } \
```

Would any of you have a solution that works with Nano Server. The ADD instruction will bring content down, but looking for a scripted way to install and cleanup. Invoke-Command does not work and the WebClient class is not present. I've found an HttpClient class but am having issues downloading files with it.

**Comment by friism** [comment]
@neilpeterson I'm continuing this work here: https://github.com/docker-library/golang/pull/92

**Pull request merged**
