### PR TITLE
Ddd call-out to Docker for Windows

### PR DESCRIPTION
**Pull request by friism**

### CODE REVIEW

**Comment by jhowardmsft** [comment]
As per slack, does not LGTM

**Comment by PatrickLang** [comment]
Can you do a separate PR with just the link to the Docker for Windows beta? I think that is a good callout

**Comment by friism** [comment]
@PatrickLang @jhowardmsft updated

**Comment by jhowardmsft** [comment]
What build does D4W install? Master? If not, it comes down to the same thing as discussed and similarly does not LGTM. Master should be fixed again via https://github.com/docker/docker/pull/27690, but the workaround is to manually create `c:\programdata\docker` until its merged.

**Comment by PatrickLang** [comment]
Ping @taylorb-microsoft @enderb-ms can you look at this one?

**Comment by scooley** [comment]
Closing because we re-wrote and redirected the page.

**Pull request closed without merging**
