### PR TITLE
use docker for windows for win10 quickstart

### PR DESCRIPTION
**Pull request by friism**
I'm opening this for discussion to see what @enderb-ms and @PatrickLang think.

### CODE REVIEW

**Comment by PatrickLang** [comment]
Can you fix the conflict? I think the 17.03 version update conflicted with this

**Comment by PatrickLang** [comment]
I think we should clarify the command line uses PowerShell but otherwise LGTM. @enderb-ms @taylorb-microsoft  any feedback?

**Comment by enderb-ms** [comment]
LGTM

**Comment by friism** [comment]
@PatrickLang addressed your comment.

**Pull request merged**
