### PR TITLE
Update to docker version 1.13.0-rc1

### PR DESCRIPTION
**Pull request by caveman-dick**

### CODE REVIEW

**Comment by taylorb-microsoft** [comment]
@enderb-ms can you look at this?  The change looks good but question is should we use the oneget provider?  or a 'latest' link?

**Comment by PatrickLang** [comment]
Shouldn't we stick with v1.13 which is in code freeze?

We have another page with manual steps which I think is more appropriate for unreleased versions:
https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/docker/configure_docker_daemon.md
"If you would like to use an in-development version of the Docker Engine and client instead, you can use the steps that follow. This will install both the Docker Engine and client. Otherwise, skip to the next section."

**Comment by caveman-dick** [comment]
The problem is version  1.13 no longer exists on that link and the command fails. Sorry should've made that clear in the PR.  I agree a latest link would be better...

**Comment by PatrickLang** [comment]
Here's where v1.13 went:
https://test.docker.com/builds/Windows/x86_64/docker-1.13.0-rc1.zip

**Comment by friism** [comment]
I agree with @PatrickLang, https://test.docker.com/builds/Windows/x86_64/docker-1.13.0-rc1.zip would be a good way to go

**Comment by caveman-dick** [comment]
Ok updated to 1.13.0-rc1, however would it be preferable to close this and re-submit so that there is only the one commit?

**Comment by friism** [comment]
(also note that these are temporary measures - once 1.13 GAs, you can lock into that)

**Comment by scooley** [comment]
The windows 10 walkthrough was failing so I accepted a PR to bump the version to 1.14 (reported by multiple people).

If there is a better way to resolve this, please feel free.
ping @friism @taylorb-microsoft @PatrickLang @enderb-ms

**Pull request closed without merging**
