### PR TITLE
Changed CMD to a sleep rather than a ping

### PR DESCRIPTION
**Pull request by knom**

### CODE REVIEW

**Comment by scooley** [comment]
ping @enderb-ms @PatrickLang

**Comment by neilpeterson** [comment]
I do agree that with IIS in particular, the run command is difficult and that the current example is not ideal. Using Start-Sleep seams like a better example than ping. 

The proposed change could be simplified a bit:

```none
while ($true) {Start-Sleep 10}
```

Also, I have not used it myself, but @taylorb-microsoft built this script for this cause. 

https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-server-container-tools/Wait-Service

**Comment by knom** [comment]
Oh sure.. you're right :) 
Could have used $true in the first place...

**Comment by knom** [comment]
Looking at WaitService it looks like an interesting alternative as well!

**Comment by scooley** [comment]
Conflicts :(.  @PatrickLang, are these changes still relevant?

**Comment by PatrickLang** [comment]
@mylesbkeating1993 can you see if this is still needed?

Myles is making other changes to the IIS sample, I'll check with him on it.

**Comment by scooley** [comment]
@mylesbkeating1993

**Comment by jhowardmsft** [comment]
Personally I would prefer a waitservice type of thing. Or even `Wait-Process w3c` (or whatever the worker is for IIS).

**Comment by taylorb-microsoft** [comment]
@jhowardmsft - Wait-Process w3c doesn't work, that was my original idea when I wrote Wait-Service (https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-server-container-tools/Wait-Service) which accomplishes the same but handles delayed startup, restart and recycling.

**Comment by StefanScherer** [comment]
I don't think this is needed, as the official iis Dockerfile uses `ServiceMonitor.exe` -> https://github.com/microsoft/iis-docker/blob/master/windowsservercore/Dockerfile#L7

**Comment by taylorb-microsoft** [comment]
Closing as the IIS image is now using a ServiceMonitor mechanism.    https://github.com/microsoft/iis-docker/blob/master/windowsservercore/Dockerfile

**Pull request closed without merging**
