### PR TITLE
benarm-wmi-v2 - code cleanup

### PR DESCRIPTION
**Pull request by mdragan**
Code cleanup

### CODE REVIEW

**Comment by scooley** [comment]
Hey @BenjaminArmstrong, can you check out these changes and if we merge them in, I'll push the changes over to your repo as well?

**Comment by BenjaminArmstrong** [comment]
Looks good - go for it

**Comment by scooley** [comment]
@mdragan sorry for the latency. Looks like there's a conflict.  Once that's resolved, I'll merge it in :)

**Comment by mdragan** [comment]
@scooley - no problem (:

**Comment by scooley** [comment]
Thank you :)

**Pull request merged**
