### PR TITLE
Upgrade steps using OneGet provider

### PR DESCRIPTION
**Pull request by PatrickLang**
@dwaiba pointed out that the steps won't upgrade to the latest version of Docker in #580 . I'm proposing adding this as a tip to clarify how to check for and install new versions.

### CODE REVIEW

**Comment by scooley** [comment]
Looks good to me.  Are you looking for specific review?

**Comment by PatrickLang** [comment]
I wanted to discuss with @dwaiba since this would conflict with #580. We should take one PR or the other. I think this is the same intent as #580 with more specific detail

**Comment by PatrickLang** [comment]
@StefanScherer @pcgeek86 do either of you have feedback on this?

**Comment by StefanScherer** [comment]
@PatrickLang I used https://github.com/OneGet/MicrosoftDockerProvider#update-docker a couple of times, and the following steps also worked in my workshop last week:

```
Install-Package -Name docker -ProviderName DockerMsftProvider -Update -Force
Start-Service docker
docker version
```

Any reason why the `-Update` doesn't work?

**Comment by PatrickLang** [comment]
@StefanScherer ah yes, I missed that

**Comment by PatrickLang** [comment]
Thanks! I'll get this merged

**Pull request merged**
